# Numpy Random Examples at work

## Numpy
Numpy is a module for Python programming. Numpy allows you collect numerical data and put them in arrays and do manipulations or calculations on this data. 

### Simple Random Data in action


*Simple Random Data* offers 10 different functions to choose from. We are offered a selection of possibilities for creating random values.

In [4]:
import numpy as np  
# Importing the numpy package in order to find some values in action

We are going to look at various functions in the Simple Random Data range .


We will start will the rand function. We will ask the function to supply us with 5 random values.

In [5]:
np.random.rand(5)

array([0.6991505 , 0.27523755, 0.65114686, 0.13965811, 0.64557835])

These values are from a uniform distribution between 0 and 1.

We can now compare this function with the randn function.Both are quite similar, however, as rand work with uniform distribution, randn works with normal Gaussian distribution.

In [6]:
np.random.rand(5)

array([0.90588447, 0.47198671, 0.55386816, 0.353695  , 0.51200226])

As with other functions sampled from the normal distribution , the centre is focused around the mean and values close to the mean have a higher chance of appearing compared to those values found above in rand.

We can also create arays of random floats such as below : where 3 is the rows and 5 is the columns required.


In [7]:
np.random.randn(3,5)

array([[-0.50822315, -1.62334063, -1.55464347,  1.48214253,  0.32008109],
       [-1.81124347, -0.65113166, -1.35802104, -0.29959018, -0.90656221],
       [-0.2717958 ,  0.66871852, -0.07021234, -0.20231047, -1.54235099]])

randint is another function under the Simple Random branch.It offers the random selection of values where the lower paramenter is included and higher is excluded.The output could be a single integer or an array of integers



In [8]:
np.random.randint(5, size=10)
# The values to choose from are from 0 to 4, and 10 values will be created

array([3, 0, 0, 1, 1, 2, 2, 0, 2, 0])

I could also require an array of random values. Below is an example using randint

In [9]:
>>> np.random.randint(5, size=(3, 5))
# where values are chosen from 0 to 4, and created in an array of 3 roes and 5 columns

array([[2, 1, 2, 1, 4],
       [4, 0, 1, 3, 4],
       [4, 0, 1, 1, 1]])

### Permutations

The  Permutations function offers 2 methods of creating random values: 
* Shuffle and 
* Permutation 

In [ ]:
Shuffle:Here the sequence is shuffled inits place

In [14]:
s = np.array([1,2,3,4,5,6])
# I create an array with values
np.random.shuffle(s) 
# The function shuffle runs on my set of numbers in set s
s
#  I call on s to be shown.
  

array([2, 4, 5, 1, 3, 6])

Lets run the same set of numbers now with the Permutation function

In [16]:
s = np.array([1,2,3,4,5,6])
np.random.permutation(s) #  So here a new array is created and printed below, however set s does not change


array([2, 6, 3, 4, 5, 1])

In [17]:
s # Here I elicit s and we see there is no change in the value order

array([1, 2, 3, 4, 5, 6])

### Distributions in action

Under the numpy random range of function we find the distribution branch of functions. It offers a wider range of functions from a variety of distributions to find random values.

Examples of some are offered below: